# ─────────────────────────────────────────────
#  NAMESPACE
#  kubectl apply -f 00-namespace.yaml
# ─────────────────────────────────────────────

apiVersion: v1
kind: Namespace
metadata:
  name: hiqode
  labels:
    app: hiqode-demo
